version: "3"
services:
  lmeasure:
    image: melizalab/lmeasure-svc
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --access-logfile - --error-logfile - --bind :5000 --workers 4 app:app
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
